XenitAB/terraform-modules

modules/kubernetes/opa-gatekeeper/files/gatekeeper-values.yaml

This disables the priority class set by default in the gatekeeper Helm chart which is `system-node-critical`. The reason this needs to be done is because only "newer" >1.17 clusters will allow use of this priority class outside of the kube-system namespace. This change should be reverted when all clusters run the latest version of Kubernetes.
https://github.com/kubernetes/kubernetes/issues/78383

Disable priority class

---

modules/azure/core/README.md
modules/azure/core/network.tf
modules/azure/core/variables.tf
validation/azure/core/main.tf

Closes #152
**INTRODUCES BREAKING CHANGE**
A new property is added to the vnet_config object (dns_server). Can be empty list ([]) if not needed.

azure/core: add dns_servers property to vnet_config

---

modules/kubernetes/aks-core/main.tf
modules/kubernetes/eks-core/main.tf
modules/kubernetes/fluxcd-v2-github/README.md
modules/kubernetes/fluxcd-v2-github/main.tf

Fix following warning:
registry.terraform.io/hashicorp/github, for users on Terraform 0.13 or greater, this provider has moved to
integrations/github.

GitHub provider move to integrations

---

modules/kubernetes/ingress-nginx/main.tf

This helm chart includes controller v.0.45.0 and solves CVE-2021-3450
and CVE-2021-3449

Update ingress-nginx to v.3.27.0

---

modules/kubernetes/prometheus/templates/values-extras.yaml.tpl

These values is currently hard-coded.
It's supposed to only look at XKF features.

Add resource limits on prometheus

---

modules/kubernetes/ingress-healthz/templates/values.yaml.tpl

Removes the need to rely on mutation webhooks for setting a correct security context.

Set container security context for ingress-healthz

---

modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/ingress-nginx/README.md
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl
modules/kubernetes/ingress-nginx/variables.tf
validation/kubernetes/ingress-nginx/main.tf

Adds options to set name override, which is appended to the end of the name, and internal lb settings.
This is to enable public/private ingress use cases. The name override will be used in the namespace, deployment name, and ingress class. If nothing is set the behavior will be the same as before.

Add ingress nginx name override and internal setting

---

modules/kubernetes/fluxcd-v2-azdo/main.tf

The flux provider pins the flux version by default now, so there is no need to do this in the module also.

Remove version pinning from flux

---

modules/azure/aks-global/README.md
modules/azure/aks-global/acr.tf
modules/azure/governance-global/README.md
modules/azure/governance-global/delegate-acr.tf

Grants permission to members of resource groups to view Container Registry in Azure Portal.
Fixes #249

Add group and permissions for ACR reader

---

modules/kubernetes/aks-core/modules.tf
modules/kubernetes/linkerd/README.md
modules/kubernetes/linkerd/charts/linkerd-extras/Chart.yaml
modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-identity-issuer.yaml
modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-proxy-injector.yaml
modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-sp-validator.yaml
modules/kubernetes/linkerd/main.tf
modules/kubernetes/linkerd/templates/values.yaml.tpl

Changes:
* `aks-core`: depends_on `cert_manager` and `opa_gatekeeper`
* `linkerd`: align expiry dates
* `linkerd`: set webhookFailurePolicy to hard fail
* `linkerd`: namespaceSelector changed to `control-plane="true"`

linkerd webhook and expiry

---

.github/workflows/check.yaml
.github/workflows/latest-version.yaml
modules/kubernetes/aks-core/README.md
modules/kubernetes/eks-core/README.md
modules/kubernetes/fluxcd-v2-azdo/README.md
modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-azdo/templates/azdo-proxy-values.yaml.tpl
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitor.yaml

This change updates azdo proxy to the latest version. The major change is that token generation is no longer done by Terraform but rather in the app.

Update azdo proxy to latest version

---

modules/azure/aks-global/main.tf
modules/azure/aks/main.tf
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/core/main.tf
modules/azure/github-runner/main.tf
modules/azure/governance-global/main.tf
modules/azure/governance-regional/main.tf
modules/azure/governance/main.tf
modules/azure/hub/main.tf
modules/kubernetes/aks-core/main.tf
modules/kubernetes/loki/main.tf

There is currently a bug in azurerm version 2.62.0.
https://github.com/terraform-providers/terraform-provider-azurerm/issues/12060
We need to ignore updates of the provider until it is fixed and released. Generally new azurerm versions are released on fridays so this should be kept at least until then.

Ignore azurerm update

---

modules/kubernetes/ingress-healthz/main.tf

Latest version of the nginx helm charts breaks pod disruption budgets. This reverts and freezes the version until it is fixed.
bitnami/charts/pull/6910

Revert nginx helm chart version

---

modules/kubernetes/ingress-healthz/main.tf

Issue has now been fixed in bitnami chart so we should be able to update again.

Remove update ignore for ingress healthz

---

modules/kubernetes/README.md

Link destination does not exist, causing issues for docusaurus

Remove aws-calico link from kubernetes docs

---

modules/kubernetes/linkerd/templates/values.yaml.tpl

This is a small change which sets the linkerd proxy to by default output
logs as json instead of plain text. The reasoning is that log collectors
such as datadog prefer structured log data so the majority of users
prefer this behavior instead of plain text. It is still possible to
change the format to plain text with an annotation on the pod.

Change linkerd proxy default log format

---

modules/aws/eks/README.md
modules/aws/eks/eks.tf
modules/aws/eks/variables.tf
validation/aws/eks/main.tf

Enable private endpoints on the EKS cluster,
this way the cluster can communicate inside the VPC when communicating internally.

Enable CIDR definition in EKS clusters

---

modules/kubernetes/aad-pod-identity/README.md
modules/kubernetes/aad-pod-identity/main.tf
modules/kubernetes/aad-pod-identity/templates/values.yaml.tpl
modules/kubernetes/aad-pod-identity/variables.tf

It was easier to always tolerate all taints rather than make it an option.

Make aad pod id tolerate all taints

---

modules/kubernetes/eks-core/modules.tf

If this isn't done CSI is unable to start due to SecurityContext

Make OPA ignore csi-secrets-store-provider-aws ns

---

modules/aws/core/README.md
modules/aws/core/main.tf
modules/aws/eks-global/README.md
modules/aws/eks-global/main.tf
modules/aws/eks/README.md
modules/aws/eks/eks.tf
modules/aws/eks/main.tf
modules/aws/eks/outputs.tf
modules/aws/eks/templates/update-eks-cni.sh.tpl
modules/aws/irsa/README.md
modules/aws/irsa/main.tf
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/main.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/fluxcd-v2-azdo/README.md
modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-azdo/templates/cluster-tenants.yaml
modules/kubernetes/fluxcd-v2-azdo/templates/tenant.yaml
modules/kubernetes/fluxcd-v2-azdo/variables.tf
modules/kubernetes/fluxcd-v2-github/README.md
modules/kubernetes/fluxcd-v2-github/main.tf
modules/kubernetes/fluxcd-v2-github/templates/cluster-tenants.yaml
modules/kubernetes/fluxcd-v2-github/templates/tenant.yaml
modules/kubernetes/fluxcd-v2-github/variables.tf
validation/kubernetes/fluxcd-v2-azdo/main.tf
validation/kubernetes/fluxcd-v2-github/main.tf

This change fixes the owner id in eks-core for external-dns, and the cluster directories for fluxv2. The changes in fluxv2 is required so that two clusters do not attempt to write to the same directory.

Update flux and external-dns to handle blue green deployments.

---

modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf

Else the ingressClass default value won't be set if using multiple
ingressClasses.

Set depends_on ingress_nginx to azad & healthz

---

modules/kubernetes/eks-core/modules.tf

For some reason the mutation don't seem to trigger for the statefulset
created by the prometheus operator.

Disable OPA in prometheus ns in EKS

---

modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/falco/README.md
modules/kubernetes/falco/main.tf
modules/kubernetes/falco/templates/falco-values.yaml.tpl
modules/kubernetes/falco/variables.tf
validation/kubernetes/falco/main.tf

Solves #378, sadly amazon linux kernel don't seem to be new enough to use eBPF but the pre-built kernel should work just fine.

Disable eBPF on AWS

---

modules/kubernetes/azad-kube-proxy/main.tf
modules/kubernetes/azad-kube-proxy/templates/values.yaml.tpl

This PR bumps the version of azad-kube-proxy from `v0.0.24` to `v0.0.26` where the metrics and health checks are now running on a separate port (https://github.com/XenitAB/azad-kube-proxy/pull/298).
It also removes a duplicate environment variable of PORT which is already set by `application.port`.

Bump azad-kube-proxy to enable separate port for metrics and health checks

---

CHANGELOG.md
modules/azure/aks/aks.tf
modules/kubernetes/cluster-autoscaler/templates/values.yaml.tpl

This fix allows the autoscaler in EKS and AKS to scale down nodes with local storage. Without this the autoscaler will rarely scale down nodes. Users should not expect local storage to always be available so this should not cause any issues.

Allow scale down for nodes with local storage

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

This PR enables tracing for datadog as well as adds `x-forwarded-for` header to services.

ingress-nginx fixes

---

CHANGELOG.md
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/namespace.tf
modules/kubernetes/eks-core/variables.tf

This just enables resource limit ranges for EKS deployments. Not really sure why it was disabled but that does not really matter now anyways.

Enable default resources in EKS core

---

CHANGELOG.md
modules/kubernetes/aks-core/namespace.tf
modules/kubernetes/eks-core/namespace.tf

This change fixes issues when creating new tenant namespaces as it would not wait for the namespace to be created before creating resources in it.

Fix namespace resources dependencies

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/charts/ingress-nginx-extras/Chart.yaml
modules/kubernetes/ingress-nginx/charts/ingress-nginx-extras/templates/certificate.yaml
modules/kubernetes/linkerd/charts/linkerd-extras/Chart.yaml
modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-identity-issuer.yaml
modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-proxy-injector.yaml
modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-sp-validator.yaml

This change sets a value for a Certificate revision history. This value controls how CertificateRequests are kept. The default value is nil, meaning CertificateRequests will never be cleaned up. Letsencrypt certificates dont really have this problem as they are only renewed every 3 months. However linkerd certificates will produce a lot of CertificateRequests as thos Certificates are renewed multiple times a day.
A logical reasoning would be that a reasonable default value would be set by the controller, but it seems like this will never happen.
Reference to the cert manager docs.
https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate

Set revision history to all created cert manager certifiates

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/templates/prometheus.yaml

This to be nicer to thanos receiver when sending data to it.
We can wait a few extra miliseconds for this data to come to the receiver, as long as it comes.

Prometheus set queue config in remote write

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/prometheus.yaml

This changes fixes some wrong conclusions we made previously in regard to fixes in the remote write. This change is based on a change to the default value in the next release of Prometheus.
https://github.com/prometheus/prometheus/pull/9634

Fix prometheus remote write queue config

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/prometheus.yaml

This change decreases the max shards from the default 200 to 100. The reasoning for this is to reduce the risk of sending a large amount of requests when remote write starts to fail. By reducing the max shard count we reduce the concurrency for each Prometheus instance.

Decrease max shards

---

CHANGELOG.md
modules/kubernetes/README.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/eks-core/variables.tf
modules/kubernetes/falco/templates/falco-values.yaml.tpl
modules/kubernetes/goldpinger/README.md
modules/kubernetes/goldpinger/main.tf
modules/kubernetes/prometheus/README.md
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitor.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/values.yaml
modules/kubernetes/prometheus/main.tf
modules/kubernetes/prometheus/templates/values-extras.yaml.tpl
modules/kubernetes/prometheus/variables.tf

I have for a while been seeing a lot of false positives from goldpinger that just dont make sense. Personally I do not see a need for goldpinger as it does not do the job it advertises well. I think it is best to just remove goldping as nobody relies on it as a health metrics. One less daemonset in our clusters.

Remove goldpinger from aks and eks core and deprecated goldping module

---

CHANGELOG.md
modules/kubernetes/csi-secrets-store-provider-aws/charts/csi-secrets-store-provider-aws/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitor.yaml

Closes #356
Enables podmonitor for Prometheus to monitor "secrets-store-csi-driver" for both Azure and AWS.

Add podmonitor for secrets-store-csi-driver

---

.github/workflows/changelog.yaml
.github/workflows/check.yaml
CHANGELOG.md

This change fixes the changelog check for PRs originating from forks. The new checker will also check the content of the changelog to make sure that it is correct.

Change the method of checking changelog updates

---

CHANGELOG.md
modules/kubernetes/aad-pod-identity/main.tf
modules/kubernetes/aks-core/aks-core-extras.tf
modules/kubernetes/azad-kube-proxy/main.tf
modules/kubernetes/cert-manager/main.tf
modules/kubernetes/cluster-autoscaler/main.tf
modules/kubernetes/csi-secrets-store-provider-aws/main.tf
modules/kubernetes/csi-secrets-store-provider-azure/main.tf
modules/kubernetes/datadog/main.tf
modules/kubernetes/eks-core/aks-core-extras.tf
modules/kubernetes/external-dns/main.tf
modules/kubernetes/falco/main.tf
modules/kubernetes/fluxcd-v1/main.tf
modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-github/main.tf
modules/kubernetes/ingress-healthz/main.tf
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/linkerd/main.tf
modules/kubernetes/loki/main.tf
modules/kubernetes/opa-gatekeeper/main.tf
modules/kubernetes/prometheus/main.tf
modules/kubernetes/reloader/main.tf
modules/kubernetes/starboard/main.tf
modules/kubernetes/velero/main.tf

This change will reduce the amount of secrets created by Helm to store chart history. The default max history is 0 meaning that there is no limit. We dont really use the chart history as we do not rollback on failure. Setting it to 3 is just what I think is a reasonable number.

Set max history for helm releases

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/values.yaml

Prometheus needs a lot of head room in case of a WAL replay so the limit needs to be high. These settings should be adjusted as we move to agent mode in the next Prometheus release.

Adjust prometheus resource requests to fix OOM Kill

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitors.yaml

This change fixes a multidoc file separator in the prometheus extras Helm chart. Currently some monitors are not created because of this.

Fix multi doc separator in prometheus monitors

---

CHANGELOG.md
modules/azure/core/README.md
modules/azure/core/routes.tf
validation/azure/core/main.tf

This fixes the issue described in the following issue:
https://github.com/XenitAB/terraform-modules/issues/303
Now we're forking on the next_hop_type and remove the
next_hop_in_ip_address if it's not a VirtualAppliance route.
Let's hope it solves the problem. :^)

azure/core: add support for non VirtualAppliance routes

---

modules/azure/aks/aks.tf

This change fixes issues when running plan after creating a spot instance. We have to specify the taints and labels added by Azure when a spot instance is created to not create a state conflict.
Skipping changelog as it just fixes a PR that was just merged.

Fix conflicts with taints and labels set by Azure on spot node pools

---

CHANGELOG.md
modules/azure/aks/aks.tf

This changes the expander strategy from the default random to least waste. Hopefully this will result in the cluster autoscaler selecting the right type of instance class when scaling up. It is possible to select multiple expanders but that is not currently supported by AKS. There is an issue in the provider which tracks this hashicorp/terraform-provider-azurerm/issues/13900.
Refer to the cluster autoscaler documentation for detailed information.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders

Set AKS cluster autoscaler expander strategy to least waste

---

CHANGELOG.md
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/Chart.yaml
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/templates/grafanaagent.yaml
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/templates/loginstance.yaml

Please note that `externalLabels` are set in two different places for logs and metrics, which is beautifully described in the following comment: https://github.com/grafana/agent/issues/1035#issuecomment-953607160
We are also changing the name from `clusterName` to `cluster` which replaces the "default" cluster label (which was `grafana-agent/grafana-agent`). This may, or may not, cause issues in the future - but I've been promised by @NissesSenap that he'll solve it using jsonnet. ;^)
This will resolve the following issue: https://github.com/XenitAB/terraform-modules/issues/495

grafana-agent: Add externalLabels to logs

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/k8s-cluster-role.tf
modules/kubernetes/aks-core/k8s-role-binding.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/k8s-cluster-role.tf
modules/kubernetes/eks-core/k8s-role-binding.tf

In the future developers should be able to use the reports generated from starboard to gain insights on how there configuration of their deployments is done together with CVE:s.

Give users access to read/delete starboard reports

---

CHANGELOG.md
modules/kubernetes/external-dns/main.tf

This change updates the external-dns Helm chart as the Azure MSI issues were fixed in the 10.2 release.

Update external-dns Helm chart

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/prometheus.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/values.yaml
modules/kubernetes/prometheus/main.tf
modules/kubernetes/prometheus/templates/values.yaml.tpl

Upgrade kube-prometheus-stack to 30.0.0, this to get the latest prometheus-operator version so we can use
prometheus in agent mode.
Also run prometheus in agent mode, this to lower resource usage and a smarter way of handling WAL.

Set prometheus in agent mode and upgrade kube-prometheus-stack to 30.0.0

---

CHANGELOG.md
modules/kubernetes/vpa/templates/vpa-values.yaml.tpl

Enabling agent mode in Prometheus removes the ability to run queries. The current VPA configuration is setup to use cadvisor metrics from Promtheus to calculate its recommendation. This is not possible anymore. The fix right now is to switch to the default checkpoint method which stores metrics in a CRD.
We should in the future have a look at if this is the best solution, or if there is a better one out there.

Change VPA storage from prometheus to checkpoint

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitors.yaml

This change fixes the labels and label selector for the metrics services. Issues occur when private/public controllers are enabled, which cause the service monitor label selector to fail. This fix changes the labels so that both metrics services can be selected with the same selector.
Fixes #518

Fix nginx ingress service monitor selector when running multiple controllers

---

CHANGELOG.md
modules/aws/README.md
modules/aws/eks-core/README.md
modules/aws/eks-core/flow-log.tf
modules/aws/eks-core/main.tf
modules/aws/eks-core/outputs.tf
modules/aws/eks-core/route53.tf
modules/aws/eks-core/variables.tf
modules/aws/eks-core/vpc.tf
validation/aws/eks-core/main.tf

In order to be able to add network ACLs to the core setup of EKS, an EKS opinionated core module was created and the previous "generic" core module was renamed to "generic-core". Names can of course be discussed here. The new EKS opinionated core module contains copied code from "generic-core" . It would however be possible to refer to the "generic-core" module from this module but the reason for not doing that is that we allow the different code bases to diverge if needed. Could of course also be discussed.

Create opinionated EKS Core module

---

CHANGELOG.md
modules/azure/core/README.md
modules/azure/core/delegate-service-endpoint-join.tf
modules/azure/core/variables.tf
modules/azure/hub/README.md
modules/azure/hub/main.tf
modules/azure/hub/variables.tf

The azure_role_definition names needs to be unique for each Azure
tenant, which means if two different landing zones are using the same
everything else they will collide causing issues for the second one.
This fix should be backward compatible, only moving 'role' from being ha
hard coded string into a default variable that new landing zones will be
able to change if needed.

azure: Add prefix to role definitions

---

CHANGELOG.md
modules/azure/core/routes.tf

This is **not** used by XKF by default and does not affect it if routes haven't been configured.
We were looping through var.routes which contains a list of all the
route+subnet combinations, which would work for the first route but not
for the second and third because the subnet already had a route table
associated.
With this fix, we are moving the configuration to use the correct
var.route_config instead which is the same as the route_tabe
configuration.
This shouldn't cause any big issue, but will temporarily remove the
route association from the subnet and then add it again. But after this
fix, we will be able to use multiple routes for a route table - as god
intended it to be. :^)

azure/core: Fix bug in route table association

---

CHANGELOG.md
modules/kubernetes/azad-kube-proxy/templates/values.yaml.tpl

This to minimize the risk of getting evicted during high load on the kubernetes nodes.

Azad-kube-proxy define resources

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

Edvin saw an issue with the pods being assigned to nodes in the same availability zones, this would result in if a zone goes down, so will our pods. So I add podAntiAffinity to spread pods on nodes based on availability  zones.
First time configuring this, please consider anything.
Fixes #538

Add podAntiAffinity to Ingress-nginx

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitors.yaml

Seems like the prometheus operator has removed the label `app: prometheus`. This changes fixes the label selector so that we get meta metrics.

Fix pod label selector for Prometheus monitor

---

CHANGELOG.md
modules/kubernetes/prometheus/templates/values.yaml.tpl

This change removes the collection of secrets and configmaps from kube state metrics. My reasoning is that we do not use these metrics at all so there is no real point of collecting them. They only create a large amount of data which has to be remotely sent and received.

Remove secret and configmap data collection form kube state metrics

---

CHANGELOG.md
modules/kubernetes/aks-core/networkpolicy.tf
modules/kubernetes/eks-core/networkpolicy.tf

For cluster using var.kubernetes_network_policy_default_deny = false,
these new network policies are causing issues (all traffic is blocked).
Fixes #569

aks/eks core: fix network policy bug

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

This looks like a major change from the outside but hopefully is not one. The main difference is dropping support for `networking.k8s.io/v1beta` and switching to `networking.k8s.io/v1`. The consequence of this is dropping support for clusters older than 1.19, which we are not running anyway.
We are going to have to test the upgrade before merging this just to be sure. I have also done some reading in the Helm chart and project changelogs to see if there are any obvious issues.
https://github.com/kubernetes/ingress-nginx/blob/main/Changelog.md
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/CHANGELOG.md
One issue is the change from ingress class annotations to the IngressClass resource. We are already create an IngressClass resource but do not enforce the use of …

Update Ingress Nginx version

---

CHANGELOG.md
modules/kubernetes/external-dns/main.tf

This change updates external-dns. A major difference is that it now requires Kubernetes 1.19 or higher.

Update external dns version

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/namespace.tf
modules/kubernetes/node-local-dns/README.md
modules/kubernetes/node-local-dns/main.tf
modules/kubernetes/node-local-dns/variables.tf

After a few weeks of usage of node-local-dns we started to see issues with talking to the dns.
I don't know why this happens but after reading up on node-local-dns I understand why we need this rule.
This IP is very specific and I don't add any logic around it since it's the real IP of coreDNS service.

Node local dns tenant network networkpolicy

---

CHANGELOG.md
modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-github/main.tf

This bumps git-auth-proxy to include case-insensitive path matching. See https://github.com/XenitAB/git-auth-proxy/releases/tag/v0.6.0 for more info.

Bump git-auth-proxy to v0.6.0

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/prometheus.yaml

This change aligns some settings with the current remote write defaults and decreases the max shards to reduce the amount of parallel requests.

Change remote write settings to align with best practices

---

CHANGELOG.md
modules/kubernetes/cert-manager/main.tf

The major change here is that all CRD versions other than v1 are removed. We need to do a quick inventory och clusters to determine that old versions are not being used. Probably not the case as v1 has been present for a while but we still need to make sure.

Update cert-manager version

---

CHANGELOG.md
modules/kubernetes/starboard/main.tf
modules/kubernetes/starboard/templates/starboard-values.yaml.tpl

The current default value is trivy 0.22.0 and the version we need
for aadpodidentity is 0.23.0.

Hardcode image version for starboard job

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

This to be able to support both public and private ingress-nginx.
This was default before but this was changed upstream.
For more information you can read: https://github.com/kubernetes/ingress-nginx/issues/8276 and https://github.com/kubernetes/ingress-nginx/issues/8144

set electionID in ingress-nginx

---

CHANGELOG.md
modules/kubernetes/aks-core/namespace.tf

Without this it's not possible to forward traffic to node-local-dns.

Add 169.254.25.10 to default-deny networkpolicy

---

CHANGELOG.md
modules/aws/eks/eks.tf
modules/azure/aks/aks.tf

This change will hopefully protect against situations where there are two node pools and someone attempts to replace the node pool in one shot. Normally Terraform will first delete the existing node pool which will start the eviction process before creating the new node pool. This is normally not an issue but not idea either. This change will make sure that there are nodes for pods to be evicted to before draining the old nodes.

Create new EKS and AKS node pools before deleting existing node pools

---

CHANGELOG.md
modules/kubernetes/falco/templates/falco-values.yaml.tpl

Seems like AWS have removed there extra docker runtime that was available on older nodes.
After disabling docker I can now see data in AWS again.

Falco aws disable docker

---

CHANGELOG.md
modules/kubernetes/README.md

Deprecate the loki and xenit module.
Removing the xenit module as work going forward is not going to use the proxy.
Will remove all deprecated modules in one go in a future PR later.

Deprecate loki and xenit module

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/eks-core/variables.tf
validation/kubernetes/aks-core/main.tf
validation/kubernetes/eks-core/main.tf

By default, Promtail in XKF in the aks-core and eks-core modules is set up to ships logs from all platform namespaces (i.e. the tenant namespaces are ignored). This PR makes it possible, on the aks-core and eks-core module level, to configure the namespaces that Promtail shall ignore to allow for a more flexible setup.

Add variable for excluding promtail namespaces

---

CHANGELOG.md
README.md
modules/azure-ad/.tflint.hcl
modules/azure-ad/README.md
modules/azure-ad/azad-kube-proxy/README.md
modules/azure-ad/azad-kube-proxy/main.tf
modules/azure-ad/azad-kube-proxy/outputs.tf
modules/azure-ad/azad-kube-proxy/variables.tf
modules/azure/aks-global/README.md
modules/azure/aks-global/azad-kube-proxy.tf
modules/azure/aks-global/outputs.tf
modules/azure/aks-global/variables.tf
modules/kubernetes/azad-kube-proxy/README.md
modules/kubernetes/azad-kube-proxy/main.tf
validation/azure-ad/azad-kube-proxy/main.tf

This PR introduces a long awaited feature now enabled with using the latests terraform Azure AD provider (and with that, Microsoft Graph) where we are creating the Azure AD application used by azad-kube-proxy with terraform instead of manually.
You will now configure `aks-global` like this:
```terraform
module "aks_global" {
source = "github.com/xenitab/terraform-modules//modules/azure/aks-global?ref=[ref]"
[...]
azad_kube_proxy_config = {
cluster_name_prefix = "aks"
proxy_url_override  = ""
}
}
```
And then `aks-core` like this:
```terraform
module "aks1_core" {
source = "github.com/xenitab/terraform-modules//modules/kubernetes/aks-core?ref=[ref]"
[...]
azad_kube_proxy_enabled = true
azad_kube_proxy_config = {
fqdn                  = "aks.${var.dns_zone}"
azure_ad_group_prefix = …
```

Create Azure AD Application for azad-kube-proxy using aks-global

---

CHANGELOG.md
modules/aws/eks-global/README.md
modules/aws/eks-global/azad-kube-proxy.tf
modules/aws/eks-global/outputs.tf
modules/aws/eks-global/variables.tf
validation/aws/eks-global/main.tf

Breaking change, add support to manage azad-kube-proxy through terraform using azure-ad module in eks-global.
This continues the work done in: https://github.com/XenitAB/terraform-modules/pull/639 but for EKS.
In module module "eks_global" you need to add dns_zone
```.hcl
dns_zone = var.dns_zone
```
In module "eks2_core"
```.hcl
azad_kube_proxy_enabled = true
azad_kube_proxy_config = {
fqdn                  = "eks.${var.main_dns_zone}"
azure_ad_group_prefix = var.aks_group_name_prefix
allowed_ips           = var.eks_authorized_ips
azure_ad_app          = module.eks_global.azad_kube_proxy.azure_ad_app
}
```
Importing existing azad config.
```
ENV=qa
AZ_APP_ID=$(az ad app list --display-name "eks-${ENV}" --query "[0].appId" -o tsv)
AZ_APP_PERMISSION_ID=$(az ad app show --id ${AZ_APP_ID} …
```

eks-global azad-kube-proxy config

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

[use-forwarded-headers](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers)
If true, NGINX passes the incoming X-Forwarded-* headers to upstreams. Use this option when NGINX is behind another L7 proxy / load balancer that is setting these headers.
If false, NGINX ignores incoming X-Forwarded-* headers, filling them with the request information it sees. Use this option if NGINX is exposed directly to the internet, or it's behind a L3/packet-based load balancer that doesn't alter the source IP in the packets.

Remove 'use-forwarded-headers: "true"' from ingress-nginx

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/k8s-cluster-role-binding-get-nodes.tf
modules/kubernetes/aks-core/k8s-cluster-role.tf
modules/kubernetes/aks-core/k8s-role-binding.tf

Since nodes are cluster-wide and not namespaced resources, we need 'cluster-role-binding' instead of 'role-binding'
Tested and works :)

Fix cluster-role-binding for get-nodes role

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/main.tf
modules/kubernetes/fluxcd-v2-azdo/README.md
modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-github/README.md
modules/kubernetes/fluxcd-v2-github/main.tf

This change will protect us against accidentally removing Flux components that will result in all tenant deployments being removed.

Modify FluxV2 installation to never remove applied resource

---

CHANGELOG.md
modules/kubernetes/promtail/templates/values.yaml.tpl

Before this change, all logs from the ingress-nginx namespace were
dropped due to the massive amount of logs. This change will enable
ingress-nginx logging but drop the 2xx and 3xx entries from the
access log.

Enable ingress-nginx logs in promtail

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf

This to pass PCI scanning without any issues.

Ingress-nginx enable default certificate

---

CHANGELOG.md
modules/azure/aks/aks.tf

This is a security hardening change which disables [invoking commands](https://docs.microsoft.com/en-us/azure/aks/command-invoke) inside the cluster from the Azure API.

Disable AKS run command

---

CHANGELOG.md
modules/kubernetes/helm-crd/main.tf

Issues are caused when switching methods to apply CRDs. This forces the changes to managed fields. Should be removed eventually.

Fix CRD server side apply conflicts

---

CHANGELOG.md
modules/aws/eks/variables.tf
modules/azure/aks/variables.tf

I must have been tired when writing the AKS version check because it obviously does not work. This change accepts defeat and only checks the minor version, just as EKS.

Fix k8s version check and update supported versions

---

CHANGELOG.md
modules/kubernetes/prometheus/templates/values-metrics-server.yaml.tpl

There was a breaking change in 6.0 in the helm chart.
This solves the following error on AWS:
```shell
│ Error: YAML parse error on metrics-server/templates/deployment.yaml: error converting YAML to JSON: yaml: line 58: did not find expected '-' indicator
│
│   with module.eks2_core.module.prometheus["prometheus"].helm_release.metrics_server["metrics-server"],
│   on .terraform/modules/eks2_core/modules/kubernetes/prometheus/main.tf line 48, in resource "helm_release" "metrics_server":
│   48: resource "helm_release" "metrics_server" {
```

metrics-server take extraArgs as a list

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf

Currently we exclude this namespace manually on each cluster. There is no reason to do that.
In the long run we should create more specific rules for each namespace but that is a future issue.

Exclude prometheus ns from gatekeeper

---

CHANGELOG.md
modules/kubernetes/ingress-healthz/main.tf

This pull request fixes #696.
The previous helm chart was pulled from bitnami's repository and the version in this PR is the latest available helm chart at the point of writing.
I didn't specifically test the 12.0.3 chart but the 12.0.0 chart does work.
Tested with:
- AKS kubernetes v1.22.6

Lift ingress-healthz nginx to 12.0.3

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

This config is needed to make datadog to work with the nginx ingress controller
automatically.

Add datadog nginx-ingress-controller logs config

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/linkerd/main.tf

Fix #407
Thanks to the default disable of automountServiceAccountToken for security reasons we get the following error in linkerd2:
To upgrade to this version you need to run kubernetes 1.22
This seems to be related on how env variables is unwrapped: https://discourse.linkerd.io/t/error-linkerd2-app-not-a-valid-identity-name/1020
else linkerd-viz won't start.
```shell
26m         Normal    InjectionSkipped         deployment/example                      Linkerd sidecar proxy injection skipped: automountServiceAccountToken set to "false"
```
This should have been solved with: https://github.com/linkerd/linkerd2/pull/7117
and in release: https://github.com/linkerd/linkerd2/releases/tag/edge-21.11.1
You can read a good blog about it: …

[Breaking] Upgrade linkerd CNI to 2.11.2 and control-plane to edge-22.6.1

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/values.yaml

This is required because Prometheus is using more resources than expected and has spikes while reloading the WAL.

Increase prometheus resource request and limit

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

Using the new chroot feature in ingress-nginx 1.2.0: https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/
Also solves: https://github.com/kubernetes/ingress-nginx/issues/8686 CVE-2021-25748
By upgrading to the latest image and supports use the chroot functionality.
According to the CVE issue we are not affected by this bug thanks to that we are using the https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotation-value-word-blocklist config.
But it's still good to patch the version.

Upgrade ingress-nginx helm chart to 4.1.4 and enable chroot

---

CHANGELOG.md
modules/kubernetes/azure-metrics/charts/azure-metrics-exporter/values.yaml
modules/kubernetes/datadog/charts/datadog-extras/Chart.yaml
modules/kubernetes/datadog/charts/datadog-extras/templates/datadogagent.yaml
modules/kubernetes/external-dns/templates/values.yaml.tpl
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl
modules/kubernetes/starboard/templates/starboard-values.yaml.tpl
modules/kubernetes/vpa/templates/goldilocks-values.yaml.tpl

This to lower the amount of eviction that can happen in our cluster due to none definition of resources.
Have looked at VPA to get a good hint of what the values should be.

Set resource requests for datadog-cluster-agent, starboard-operator, ingress-nginx and goldilocks-controller

---

CHANGELOG.md
modules/aws/eks/eks.tf
modules/azure/aks/aks.tf

Remove create before destroy on node pools as this has just caused issues when recreating node pools. We should look for an alternative solution to make sure that developers do not remove node pools before adding a new one.

Remove create before destroy

---

CHANGELOG.md
modules/kubernetes/azad-kube-proxy/main.tf

Uses: https://github.com/XenitAB/azad-kube-proxy/releases/tag/v0.0.34

Upgrade azad-kube-proxy to 0.0.34

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/locals.tf
modules/azure/aks-global/outbound-ips.tf
modules/azure/aks-global/variables.tf

This is a workaround to make it possible for us to save a existing ip prefix.
In azure you can move a IP prefix, but you are unable to change the name of it.
To workaround this we have added a override variable, where you can define the name.
Ether before you create your cluster or if you have a existing cluster you need to do a few steps to make use of this variable assuming that you have moved your existing ip prefix to the aks RG.
Add the following to aks.global, assuming that you old prefix is called pip-prefix-dev-we-aks-test-0, for example.
This won't work if you don't have the `-` and a number after.
```.tf
public_ip_prefix_name_override = "pip-prefix-dev-we-aks-test"
```
```shell
tf state rm 'module.aks_global.azurerm_public_ip_prefix.aks[0]'
terraform import --var-file …
```

override public ip prefix name in aks global

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/k8s-cluster-role.tf
modules/kubernetes/aks-core/k8s-role-binding.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/k8s-cluster-role.tf
modules/kubernetes/eks-core/k8s-role-binding.tf

The tenants needs access to VPA to be able to easily get help with resource suggestions.

Give tenant access to read VPA

---

CHANGELOG.md
modules/aws/eks-global/README.md
modules/aws/eks-global/eks.tf
modules/aws/eks-global/main.tf
modules/aws/eks-global/variables.tf
validation/aws/eks-global/main.tf

Breaking change, variable `eks_admin_assume_principal_ids` need to be set. For legacy behavior:
```
data "aws_caller_identity" "current" {}
eks_admin_assume_principal_ids = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
```

Make EKS admin assume role principals configurable

---

CHANGELOG.md
modules/kubernetes/opa-gatekeeper/main.tf

Update to latest gatekeeper-lib.
These settings include support for debug containers in k8s 1.23.

Update gatekeeper to 3.9.0

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

In AWS overwrite the default internal-logger-address when having one internal and external ingress defined.
This makes it possible for us to enable chroot again.

Enable chroot in AWS again

---

.github/workflows/latest-version.yaml
modules/kubernetes/linkerd/main.tf

Changes:
* Update tf-latest-version: `v0.1.0` -> `v0.1.1`
* Fix tf-latest-version flag (was changed in earlier version)
* Ignore linkerd helm charts (they are using pre-release and shouldn't be updated automatically)

Fix tf-latest-version

---

CHANGELOG.md
modules/azure/governance-regional/delegate-kv.tf
modules/azure/governance-regional/locals.tf

When adding a certificate to a Azure Key Vault you have to manually change the permissions to be able to do so event if you are in the owners group. This PR gives owners all certificate permission in the same way as we already have for keys and secrets.

Add cert permissions to group owners

---

CHANGELOG.md
modules/aws/eks/README.md
modules/aws/eks/main.tf
modules/azure/aks-global/README.md
modules/azure/aks-global/main.tf
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/github-runner/README.md
modules/azure/github-runner/main.tf
modules/kubernetes/linkerd/README.md
modules/kubernetes/linkerd/main.tf

Changes:
* Bump `tls` provider from `3.1.0` to `4.0.1` 
* Remove deprecated parameter `key_algorithm` as it's inferred from `private_key_pem` since `4.0.0`

Bump terraform tls provider

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/csi-secrets-store-provider-azure/main.tf

Changes:
* The helm chart repository URL has changed from `https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts` to `https://azure.github.io/secrets-store-csi-driver-provider-azure/charts`

Move secrets-store-csi-driver-provider-azure helm chart location

---

CHANGELOG.md
modules/kubernetes/linkerd/main.tf

This change fixes an hones mistake of setting `early_renewal_hours` to 9 years instead of 1 year. I think the intent was to force renewal a year early but the result was renewing the certificate 8 years early instead.
This change fixes the mistake.

Fix Linkerd cert expiring 8 years too early

---

CHANGELOG.md
modules/kubernetes/linkerd/templates/values-cni.yaml.tpl
modules/kubernetes/linkerd/templates/values-viz.yaml.tpl
modules/kubernetes/linkerd/templates/values.yaml.tpl

This changes the registry used by Linkerd pods from its own registry to ghcr. The reason for this is that the default registry can cause large image pull duration at times.

Replace linkerd image registry with ghcr

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

This change skips Linkerd for traffic to port 8443 in Ingress Nginx. The reason for this is that the traffic coming from the Kubernetes API cannot go through Linkerd.

Skip Linkerd proxy for Ingress Nginx webhook

---

CHANGELOG.md
modules/kubernetes/README.md
modules/kubernetes/helm-crd-oci/README.md
modules/kubernetes/helm-crd-oci/main.tf
modules/kubernetes/helm-crd-oci/variables.tf
validation/kubernetes/helm-crd-oci/main.tf

A simple workaround to be able to use oci helm charts from terraform.

Enable a seperate helm-crd for oci helm charts

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/linkerd/main.tf

In the linkerd fork we have removed the helm chart k8s version limitation.
We also provide the helm chart through OCI.
It uses the helm-crd-oci that is fixed in: https://github.com/XenitAB/terraform-modules/pull/767

Use OCI helm chart in xenit linkerd fork

---

CHANGELOG.md
modules/kubernetes/ingress-healthz/templates/values.yaml.tpl

We don't need region in AWS until we support multi region

Make region optinal in ingress-health fqdn

---

CHANGELOG.md
modules/azure/core/README.md
modules/azure/core/variables.tf
validation/azure/core/main.tf

It's really easy to make configuration mistakes thanks to this default value.
For people not defining it you will need to set
```
unique_suffix = ""
```

Remove default value on unique_suffix in core module

---

CHANGELOG.md
modules/kubernetes/falco/main.tf
modules/kubernetes/falco/templates/falco-values.yaml.tpl

The 2.0 chart contains multiple breaking changes.
Manual work is needed due to updates in DS label selector.
```
│ Error: cannot patch "falco" with kind DaemonSet: DaemonSet.apps "falco" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"falco", "app.kubernetes.io/name":"falco"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
│ 
│   with module.aks1_core.module.falco["falco"].helm_release.falco,
│   on .terraform/modules/aks1_core/modules/kubernetes/falco/main.tf line 34, in resource "helm_release" "falco":
│   34: resource "helm_release" "falco" {
```
Run
```shell
k delete ds falco -n falco
```
And then update the falco module.

Update Falco helm chart to 2.0.16

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/main.tf
modules/azure/aks-regional/README.md
modules/azure/aks-regional/main.tf
modules/azure/aks/README.md
modules/azure/aks/main.tf
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/locals.tf
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/azure-pipelines-agent-vmss/variables.tf
modules/azure/core/README.md
modules/azure/core/main.tf
modules/azure/github-runner/README.md
modules/azure/github-runner/main.tf
modules/azure/governance-global/README.md
modules/azure/governance-global/main.tf
modules/azure/governance-regional/README.md
modules/azure/governance-regional/main.tf
modules/azure/hub/README.md
modules/azure/hub/main.tf
modules/azure/xkf-governance-global-data/README.md
modules/azure/xkf-governance-global-data/main.tf
modules/azure/xkf-governance-global/README.md
modules/azure/xkf-governance-global/main.tf
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf
validation/azure/azure-pipelines-agent-vmss/main.tf

When using images from a Community Image Gallery, the image need to be referred to by a source image ID, e.g. ` source_image_id = "/communityGalleries/xenit-d09d1810-7622-4864-9236-1a32035d35f0/images/azdo-agent/versions/1.0.0"`.
For this to work, `azurerm` provider also need to be upgraded to 3.22.0.
Upgrade instructions:
Instead of using `azure_pipelines_agent_image_name` and `azure_pipelines_agent_image_resource_group_name` for identifying the image, use `source_image_id`. Use `Resource ID` of the actual image as the value for  `source_image_id`.
Fixes: https://github.com/XenitAB/terraform-modules/issues/781

[Breaking] Image gallery support for Azure Pipelines module

---

CHANGELOG.md
modules/azure/aks/aad-group.tf
modules/azure/aks/main.tf

This is a work around which fixes a long standing issue of the role assignments being recreated when ever the AKS cluster resource is updated. 
You can read more about the work around here.
https://github.com/hashicorp/terraform-provider-azurerm/issues/15557#issuecomment-1050654295

Stop role assignment recreation on AKS cluster update

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/k8s-role-binding.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/k8s-role-binding.tf

This is part of work to support legacy deployments. All of this will be removed when the need for external tenant access to the cluster is removed.

Add custom resource edit rights to tenant service account

---

modules/azure/aks/aad-group.tf

Without this fix we get the following error:
```
│ Error: loading Role Definition List: could not find role 'Azure Kubernetes Service Edit Role'
│ 
│   with module.aks1.azurerm_role_assignment.edit["mimforum"],
│   on .terraform/modules/aks1/modules/azure/aks/aad-group.tf line 9, in resource "azurerm_role_assignment" "edit":
│    9: resource "azurerm_role_assignment" "edit" {
```

Revert role_definition_name changes in #790

---

CHANGELOG.md
modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-github/main.tf

Easy change which decreases state drift caused when the environment name is in the commit message.

Ignore commit message changes in Flux installations

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

The default value for the nginx PDB is 1, which I do not like. Would rather have it to be 2 so that only one instance is replaced at a time.

Increase nginx ingress min availible from one to two

---

CHANGELOG.md
modules/kubernetes/datadog/charts/datadog-extras/templates/datadogagent.yaml

Datadog DS agents should run on all nodes even if tainted.

Make datadog tolerate all node taints

---

CHANGELOG.md
modules/kubernetes/node-local-dns/charts/node-local-dns/templates/nodelocaldns.yaml

No real changes more than it is now built with Go 1.18 and has some dependency updates. Have tested the new version with no real improvement or worsening of performance.

Update node local dns version

---

CHANGELOG.md
modules/kubernetes/eks-core/k8s-cluster-role.tf

This was managed in another PR for AKS and it should have been done in EKS as well but we missed it.

Add secrets-store.csi.x-k8s.io to EKS tenants

---

CHANGELOG.md
modules/azure/azure-pipelines-agent-vmss/main.tf

Reverts XenitAB/terraform-modules#827. Problem solved in azurerm 3.27.0.

Revert "VMSS source_image_reference provider bug workaround"

---

CHANGELOG.md
modules/kubernetes/falco/templates/falco-values.yaml.tpl

Upstream had changed the varaible name when upgrading to v2.

Make falco use priorityClassName again

---

CHANGELOG.md
modules/azure/aks/locals.tf

This change makes it possible to use ARM VMs in AKS. It should probably not be used initially in production but gives the option to begin experimenting.

Add support for ARM VMs in AKS

---

CHANGELOG.md
modules/azure/aks-global/acr.tf

This sets all ACR SKUs to Premium. I do not see a point in running a Basic SKU as Premium includes a lot more storage. Plus the increased bandwidth does not hurt.

Change ACR SKU to Standard

---

CHANGELOG.md
modules/aws/eks/eks.tf
modules/azure/aks/aks.tf

This changes the default label added to nodes indicating the node pool it is part of. The reason is to make it obvious that it is a label set by XKF. This change could be considered breaking if people have node selectors for the `node-pool` label, but as far as I know it should not be an issue.

Add XKF prefix to node pool label

---

CHANGELOG.md
modules/azure/aks/aks.tf
modules/azure/aks/azure-metrics.tf
modules/azure/aks/main.tf
modules/kubernetes/aks-core/main.tf
modules/kubernetes/aks-core/modules.tf

This change begrudgingly adds support to set a null value for AKS name suffix due to legacy. Should be removed when no longer needed.

Allow aks name suffix to be set to null

---

CHANGELOG.md
modules/kubernetes/azad-kube-proxy/main.tf

New azad-kube-proxy version to fix HPA apiversion deprecations.

Bump azad-kube-proxy version to 0.0.36

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/prometheus/main.tf
modules/kubernetes/prometheus/templates/values.yaml.tpl

Contains a change which is breaking but solved with a force update in the helm release. This change will recreate the node exporter daemon set when updated.
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-39x-to-40x

Update Kube Prometheus Stack version

---

CHANGELOG.md
modules/kubernetes/prometheus/templates/values.yaml.tpl

This change disables API Server metrics as they produce a large amount of time series which we do not use.

Disable collecting API Server metrics

---

CHANGELOG.md
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/k8s-cluster-role-binding.tf
modules/kubernetes/eks-core/k8s-cluster-role.tf
modules/kubernetes/eks-core/k8s-role-binding.tf

Since nodes are a cluster resource they also need to have a clusterrolebinding.
This was solved in #661 for aks

get-nodes have to be a clusterrolebinding

---

CHANGELOG.md
modules/kubernetes/opa-gatekeeper/templates/gatekeeper-values.yaml.tpl

The reason why we need a custom rule is that the default rule only triggers on resources `*`
```.yaml
- apiGroups:
- '*'
apiVersions:
- '*'
operations:
- CREATE
- UPDATE
resources:
- '*'
```
But the thing with `*` is that it doesn't take sub resources in to account. So to trigger on a subresource we have to define it specifically.

OPA mutatingWebhookCustomRules trigger ephemeralContainer

---

CHANGELOG.md
modules/aws/eks/eks.tf

This to make AutoScalingGroup detect the labels needed for cluster autoscaler.
For more information see: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0
https://github.com/kubernetes/autoscaler/issues/3780

AWS Add custom tags to match node labels

---

CHANGELOG.md
modules/kubernetes/prometheus/templates/values.yaml.tpl

Dropping all apiserver metrics was a mistake as we still want metrics like `kubernetes_build_info`. This change enables the apiserver monitor but drops all metrics except very specific ones.

Include specific api server metrics

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/prometheus.yaml

This is part of the work to reduce metrics usage. It seems like the Prometheus Operator defaults to 30s while Prometheus defaults to 1m. This change just changes the interval to the default of Prometheus. This change will not override monitors which set an interval.

Change the default Prometheus scrape interval to every minute

---

CHANGELOG.md
modules/kubernetes/external-dns/main.tf
modules/kubernetes/prometheus/main.tf

Previous versions does not seem to be available any more

Update external-dns and metrics-server

---

CHANGELOG.md
modules/kubernetes/prometheus/templates/values.yaml.tpl

The instance label contain two different values on AWS and hence duplicates the number of time series

Remove instance label from API Server metrics

---

CHANGELOG.md
modules/kubernetes/prometheus/templates/values.yaml.tpl

This reverts commit a19fe555ce20545aabdcbf55ab35d9d8aa7edbae.

Revert "Remove instance label from API Server metrics (#899)"

---

CHANGELOG.md
modules/kubernetes/prometheus/README.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitors.yaml
modules/kubernetes/prometheus/main.tf
modules/kubernetes/prometheus/templates/values-x509.yaml.tpl

This to be able to monitor the mTLS cert that we use to send metrics to our central monitoring cluster.
This is how the metrics looks like:
```# HELP x509_cert_expired Indicates if the certificate is expired
x509_cert_expired{issuer_CN="Intermediate CA",secret_key="tls.crt",secret_name="xenit-proxy-certificate",secret_namespace="prometheus",serial_number="53273528899929633352051475171416450529",subject_CN="unbox"} 0
x509_cert_expired{issuer_CN="Root CA",secret_key="tls.crt",secret_name="xenit-proxy-certificate",secret_namespace="prometheus",serial_number="60338911324707063396089478656720186399",subject_CN="Intermediate CA"} 0
x509_cert_not_after{issuer_CN="Intermediate CA",secret_key="tls.crt",secret_name="xenit-proxy-certificate",secret_namespace="prometheus",serial_number="53273528899929 …
```

Add x509-certificate-exporter to prometheus ns

---

CHANGELOG.md
modules/aws/eks/README.md
modules/aws/eks/eks.tf
modules/aws/eks/templates/userdata.sh.tpl

This change adds node taint and labels as tags to their ASG. Sadly this is required because EKS does not manage this for you.

Add node labels and taints as tags to ASG

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/node-ttl/README.md
modules/kubernetes/node-ttl/main.tf
modules/kubernetes/node-ttl/templates/values.yaml.tpl
modules/kubernetes/node-ttl/variables.tf
validation/kubernetes/node-ttl/main.tf

AKS and EKS stores the status ConfigMap in different locations. This change adds a variable to allow each module to configure the namespace.

Fix Node TTL status ConfigMap namespace for AKS

---

CHANGELOG.md
modules/kubernetes/falco/main.tf
modules/kubernetes/falco/templates/falco-values.yaml.tpl

Also change from `falco.grpcOutput.enabled` to `falco.grpc_output.enabled`.
This to use the new configmap injection that the helm chart uses now a days.

Update falco to v0.33.0 and falco-exporter v0.8.0

---

CHANGELOG.md
modules/azure/aks/aks.tf

This just disables storage features that we do not use. These features create daemonsets that waste resources, even if it is not that much. We don not mount Azure Files with the file CSI driver, and we do not make snapshots of CSI disks inside of the cluster.

Disable AKS file driver and snapshot controller

---

modules/azure/core/README.md
modules/azure/core/main.tf

We assume that the log rg exists in the core module. This creation of this RG should be done in the governance module. fix #930

document the RG needed to use the core module

---

CHANGELOG.md
modules/azure/governance-regional/delegate-kv.tf

This is to fix access issues for some customers that has started to utilize certificates in Azure KeyVault

Add certificate permissions for resource group AAD group

---

CHANGELOG.md
modules/kubernetes/spegel/main.tf

There was an issue with topology keys that needed to be fixed, and the namespace name was misspelled.

Update Spegel to v0.0.4 and fix misspelled Spegel namespace

---

CHANGELOG.md
modules/kubernetes/vpa/main.tf
modules/kubernetes/vpa/templates/vpa-values.yaml.tpl

This change updates VPA to fix compatibility with Kubernetes 1.25 and move to using registry.k8s.io.

Update Goldilocks and VPA and move to using registry.k8s.io

---

CHANGELOG.md
modules/kubernetes/csi-secrets-store-provider-aws/charts/csi-secrets-store-provider-aws/values.yaml
modules/kubernetes/csi-secrets-store-provider-aws/main.tf
modules/kubernetes/csi-secrets-store-provider-azure/main.tf

This change updates the CSI secrets store version for both AWS and Azure and move to using registry.k8s.io.

Update CSI secret store and move to using registry.k8s.io

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/main.tf
modules/azure/aks-regional/README.md
modules/azure/aks-regional/main.tf
modules/azure/aks/README.md
modules/azure/aks/main.tf
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/core/README.md
modules/azure/core/main.tf
modules/azure/github-runner/README.md
modules/azure/github-runner/main.tf
modules/azure/governance-global/README.md
modules/azure/governance-global/main.tf
modules/azure/governance-regional/README.md
modules/azure/governance-regional/main.tf
modules/azure/hub/README.md
modules/azure/hub/main.tf
modules/azure/xkf-governance-global-data/README.md
modules/azure/xkf-governance-global-data/main.tf
modules/azure/xkf-governance-global/README.md
modules/azure/xkf-governance-global/main.tf
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf

This updates Azurerm to 3.51.0 and enables us to fix the SKUnaming for AKS since the API deprecations
Doesnt fix  #967, but enables us to fix it
Tested and doesnt have any breaking changes in any modules

Update AzureRM provider to 3.51.0

---

CHANGELOG.md
modules/azure/aks/aks.tf

Azure API Version 2023-02-01 and later now require sku_tier to be set to Standard instead of Paid.
Fixes #967

Switch to Standard sku_tier due to deprecations in the AzureAPI

---

CHANGELOG.md
modules/kubernetes/fluxcd-v2-azdo/templates/tenant.yaml
modules/kubernetes/fluxcd-v2-github/templates/tenant.yaml

It seems more reasonable for the provider to be automatically created in the tenants namespace. The configuration is very similar to the GitRepository that is created so this removes some burden on end users.

Manage Flux notification provider

---

CHANGELOG.md
modules/aws/eks/variables.tf
modules/azure/aks/variables.tf
validation/aws/eks/main.tf

EKS version validation was not updated. This change fixes this and locks support to only Kubernetes 1.24 and 1.25.

Fix Kubernetes version validation

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/node-ttl/README.md
modules/kubernetes/node-ttl/main.tf
modules/kubernetes/node-ttl/templates/kustomization.yaml.tpl
modules/kubernetes/node-ttl/templates/node-ttl.yaml.tpl
modules/kubernetes/node-ttl/templates/values.yaml.tpl
modules/kubernetes/node-ttl/variables.tf
validation/kubernetes/node-ttl/main.tf

This change starts the move from using the Helm provider to using Flux to install things into Kubernetes.

Migrate node-ttl to install with Flux

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/acr.tf

This task will purge images that are older than 365 days, with the exception that it will keep the 5 newest versions. This will  remove the risk of removing images that have not been updated for a year but are still being used.

Add purge task to remove old images from ACR

---

CHANGELOG.md
modules/kubernetes/eks-core/modules.tf

Exclude ingress-healthz namespace from gatekeeper

---

CHANGELOG.md
modules/azure/aks-regional/README.md
modules/azure/aks-regional/azad-kube-proxy.tf

Add azad kube proxy password to the core key vault. This will enable the separation of the kubernetes/aks_core module from the rest of aks, thereby minimizing blast radius and simplifying maintenance of aks.

Add azad kube proxy password in core key vault

---

CHANGELOG.md
modules/azure/aks/README.md
modules/azure/aks/variables.tf
modules/azure/aks/workload-identity.tf
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf
modules/kubernetes/aks-core/namespace.tf
validation/azure/aks/main.tf

This change will create a new user assigned identity with a configured federated identity to enable tenant workload identities. The reason a new identity is created is because it now has to be set per cluster. This change is not breaking as it will keep the existing aad pod identity solution until not needed anymore.

Enable workload identity service account in tenant namespaces

---

CHANGELOG.md
modules/azure/aks-regional/README.md
modules/azure/aks-regional/aad-pod-identity.tf
modules/azure/aks-regional/variables.tf
modules/azure/aks/README.md
modules/azure/aks/variables.tf
modules/azure/aks/workload-identity.tf
modules/azure/xkf-governance-global-data/README.md
modules/azure/xkf-governance-global-data/variables.tf
modules/azure/xkf-governance-global/README.md
modules/azure/xkf-governance-global/delegate-xks-rg.tf
modules/azure/xkf-governance-global/variables.tf
validation/azure/aks-regional/main.tf
validation/azure/aks/main.tf
validation/azure/xkf-governance-global-data/main.tf
validation/azure/xkf-governance-global/main.tf

I cannot find any use where delegate_resource_group is false. This just adds complexity to the namespace configuration so we should just completely remove it instead.

Remove delegate resource group from namespaces

---

CHANGELOG.md
modules/kubernetes/aks-core/main.tf

When changing the UAI name in #1075 I missed updating the datasource in aks-core.

Fix Client ID set to tenant service account

---

CHANGELOG.md
modules/kubernetes/aad-pod-identity/templates/aad-pod-identity.yaml.tpl
modules/kubernetes/azad-kube-proxy/templates/azad-kube-proxy.yaml.tpl
modules/kubernetes/cert-manager/templates/cert-manager.yaml.tpl
modules/kubernetes/control-plane-logs/templates/vector.yaml.tpl
modules/kubernetes/falco/templates/falco.yaml.tpl
modules/kubernetes/ingress-healthz/templates/ingress-healthz.yaml.tpl
modules/kubernetes/ingress-nginx/templates/namespace.yaml.tpl
modules/kubernetes/node-ttl/templates/node-ttl.yaml.tpl
modules/kubernetes/promtail/templates/promtail.yaml.tpl
modules/kubernetes/reloader/templates/reloader.yaml.tpl
modules/kubernetes/spegel/templates/spegel.yaml.tpl
modules/kubernetes/trivy/templates/trivy.yaml.tpl
modules/kubernetes/velero/templates/velero.yaml.tpl
modules/kubernetes/vpa/templates/vpa.yaml.tpl

This PR fixes syntax errors in Kubernetes manifest files that create namespaces for the kubernetes modules.

fix: missing namespace labels

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/velero/README.md
modules/kubernetes/velero/main.tf
modules/kubernetes/velero/storage.tf
modules/kubernetes/velero/templates/velero.yaml.tpl
modules/kubernetes/velero/variables.tf
validation/kubernetes/velero/main.tf

This fixes issue with `-` in the name for velero storage account, also makes the name of the SA and SA container configurable if one wants/needs to do that.

Fix: Velero storage account name format

---

CHANGELOG.md
modules/azure-ad/azad-kube-proxy/README.md
modules/azure-ad/azad-kube-proxy/main.tf
modules/azure/aks-global/README.md
modules/azure/aks-global/main.tf
modules/azure/aks-regional/README.md
modules/azure/aks-regional/main.tf
modules/azure/aks/README.md
modules/azure/aks/main.tf
modules/azure/core/README.md
modules/azure/core/main.tf
modules/azure/governance-global/README.md
modules/azure/governance-global/main.tf
modules/azure/governance-regional/README.md
modules/azure/governance-regional/main.tf
modules/azure/hub/README.md
modules/azure/hub/main.tf
modules/azure/xkf-governance-global-data/README.md
modules/azure/xkf-governance-global-data/main.tf
modules/azure/xkf-governance-global/README.md
modules/azure/xkf-governance-global/main.tf
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf

This PR bumps the version of the azuread provider to v2.50.0

chore: bump azuread provider to v2.50.0

---

modules/kubernetes/azure-policy/main.tf

This PR adds an exemption for vector to use a writable root file system

fix: allow vector to use writable root file system

---

.github/workflows/check.yaml

This PR runs the check action when a PR is labeled. This to make sure the required checks are run when updating the CHANGELOG

ci: run check when PR is labeled

---

.github/workflows/changelog.yaml

This PR bumps the version of peter-evans/create-pull-request to v6 to address this [issue](https://github.com/peter-evans/create-pull-request/issues/2790)

chore: bump peter-evans/create-pull-request to v6

---

modules/kubernetes/aks-core/namespace.tf

This PR adds  a lifecycle management tag to tenant namespace resources that will prevent the namespace from being destroyed. From now on, destorying tenant namespaces can only be made outside of Terraform/Open Tofu.

feat: prevent destruction of tenant namespaces

---

modules/kubernetes/fluxcd-v2-azdo/README.md
modules/kubernetes/fluxcd-v2-azdo/main.tf

This PR replaces the Xenit fork of microsoft/azuredevops provider with the forked provider.

refactor: use Microsoft provider for Azure DevOps

---

modules/azure/aks/README.md
modules/azure/aks/automation/main.tf
modules/azure/aks/automation/variables.tf
modules/azure/aks/modules.tf
modules/azure/aks/variables.tf

This PR adds a fix for not being able to pull the Azure region (location) name from a resource group datasource, since it returns the value `westeurope`, and not the required `West Europe`. This caused automation accounts and related resources to be re-created.

fix: wrong location name forces replacement of automation resources

---

modules/kubernetes/aks-core/modules.tf

Reverts XenitAB/terraform-modules#1185

fix: Revert Exclude ambassador namespace"

---

modules/kubernetes/aks-core/modules.tf

This PR fixes an error where the location short name was wrong, which prohibited the installation of the grafana alloy module.

fix: grafana alloy using wrong location short name

---

modules/kubernetes/README.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/nginx-gateway-fabric/README.md
modules/kubernetes/nginx-gateway-fabric/main.tf
modules/kubernetes/nginx-gateway-fabric/templates/gateway-fabric.yaml.tpl
modules/kubernetes/nginx-gateway-fabric/templates/kustomization.yaml.tpl
modules/kubernetes/nginx-gateway-fabric/variables.tf
validation/kubernetes/nginx-gateway-fabric/main.tf

This PR adds basic support for deploying `Nginx Gateway Fabric `to the cluster. The current version of the Gateway Fabric has very limited support for GatewayClass and Gateway configuration. As such, users who have previously used the Nginx Ingress Controller and are used to be able to perform advanced Nginx configuration will not be able to do this currently. However, there is a [proposal](https://github.com/nginxinc/nginx-gateway-fabric/blob/main/docs/proposals/nginx-extensions.md) in place that will add provider specific configuration in the future, and we will update the new module accordingly as they become available.

feat: add support for Nginx Gateway Fabric

---

modules/azure/aks/README.md
modules/azure/aks/aks.tf

This PR associates the default NSG with the vnet subnet.

refactor: associate AKS default NSG with vnet subnet 

---

modules/kubernetes/ingress-nginx/main.tf

This PR adds the `name` label that is required on the `ingress-nginx `namespace in order for network policicies to work properly.

fix: add required name label to ingress-nginx namespace

---

modules/kubernetes/fluxcd/main.tf

This PR adds lifecycle management to ignores changes to metadata of the flux namespace to prevent constant updates of the namespace which will be reverted automatically by flux.

fix: ignore metadata changes for flux namespace

---

modules/kubernetes/velero/main.tf
modules/kubernetes/velero/templates/velero-extras.yaml.tpl
modules/kubernetes/velero/templates/velero.yaml.tpl

Since migration of Velero was done to use Workload Identity, it hasnt worked since it wasnt supported in the old version we were running.
only upgraded it to the point were Workload Identity was introduced.
This change upgrades the chart and azure-plugin to solve that.

fix: Upgrade Velero and plugin to support Workload Identity

---

modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl

This PR makes it possible to schedule ingress nginx pods on spot nodes

feat: allow scheduling ingress-nginx on spot nodes

---

modules/kubernetes/cert-manager/templates/cert-manager.yaml.tpl

This PR makes it possible to run cert-manager on spot nodes

feat: allow cert-manager to run on spot nodes

---

modules/azure/aks/README.md
modules/azure/aks/aad-group.tf
modules/azure/aks/main.tf

This PR adds the Network Contributor role that is required to be able to create Load Balancers.

fix: add required network contributor role at subscription level

---

modules/azure/aks/variables.tf
validation/azure/aks/main.tf

This PR adjusts the aks validation to allow the creation of a cluster without any nodepools, except the system one.

fix: aks validation should allow no nodepools elements

---

modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl

When running the previous setup, we got errors due to duplicate ingresses was being created. This will fix that and only create an ingress for the public ingress.

fix: only create nginx_ingress_healthz for public ingress

---

modules/kubernetes/grafana-k8s-monitoring/main.tf
modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
modules/kubernetes/grafana-k8s-monitoring/templates/kustomization.yaml.tpl

consolidation was erronious due to flux dry-run function, it was applying the monitors before deploying the chart thus the crd's didnt exist

fix: consolidation attempt rework

---

modules/kubernetes/aks-core/locals.tf
modules/kubernetes/linkerd/main.tf

This PR fixes an indentation issue with the linkerd application, and adds the l`inkerd-viz` namespace to the list of gatekeeper namespace exlcusions.

fix: linkerd template indentation and gatekeeper exclusion
