Makefile
modules/azure/hub/main.tf
modules/azure/hub/variables.tf

* Add variable for public ip prefix lenght
* Update makefile

Update hub variable

---

.github/workflows/check.yaml
Makefile
modules/azure/aks-global/README.md
modules/azure/aks/README.md
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/core/README.md
modules/azure/governance/README.md
modules/azure/hub/README.md
modules/kubernetes/aad-pod-identity/README.md
modules/kubernetes/azdo-proxy/README.md
modules/kubernetes/fluxcd-v1/README.md
modules/kubernetes/helm-operator/README.md
modules/kubernetes/loki/README.md
modules/kubernetes/opa-gatekeeper/README.md

Add make docs

---

modules/azure/aks/README.md
modules/azure/aks/aks.tf
modules/azure/aks/variables.tf

Add suffix to cluster

---

modules/azure/aks-global/README.md
modules/azure/aks-global/outbound-ips.tf
modules/azure/aks-global/variables.tf

* Added variable for public ip prefix

Add variable for public ip prefix

---

modules/azure/aks-global/aad-group.tf
modules/azure/aks-global/aad-pod-identity.tf
modules/azure/aks-global/acr.tf
modules/azure/aks-global/locals.tf
modules/azure/aks/README.md
modules/azure/aks/aad-group.tf
modules/azure/aks/variables.tf

* Added aad group for aks_managed_identity

Add aad group aks_managed_identity

---

modules/azure/aks/modules.tf
modules/kubernetes/opa-gatekeeper/main.tf

Add azureidentityformat constraint and update gatekeeper-library

---

modules/azure/aks-global/README.md
modules/azure/aks-global/kv.tf
modules/azure/aks-global/variables.tf
modules/azure/aks/README.md
modules/azure/aks/kv.tf
modules/azure/aks/variables.tf
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/azure-pipelines-agent-vmss/variables.tf
modules/azure/governance/README.md
modules/azure/governance/delegate-kv.tf
modules/azure/governance/sp.tf
modules/azure/governance/variables.tf
validation/azure/aks-global/main.tf
validation/azure/aks/main.tf
validation/azure/azure-pipelines-agent-vmss/main.tf
validation/azure/governance/main.tf

Add unique suffix to kv name to avoid conflicts

Unique suffix in kv names

---

modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
validation/kubernetes/aks-core/main.tf

Update defaults for fluxcd_v1_config

---

.github/workflows/check.yaml
modules/kubernetes/falco/main.tf

Updates the falcosidekick chart version to include the latest host fixes.

Update falcosidekick chart version

---

modules/azure/core/README.md
modules/azure/core/delegate-service-endpoint-join.tf
modules/azure/core/locals.tf
modules/azure/core/network.tf
modules/azure/core/nsg.tf
modules/azure/core/rg.tf
modules/azure/core/subnets.tf
modules/azure/core/variables.tf
validation/azure/core/main.tf

Changes:
* Removes region loop from azure/core

azure/core: Remove region loop

---

modules/azure/hub/README.md
modules/azure/hub/locals.tf
modules/azure/hub/main.tf
modules/azure/hub/variables.tf
validation/azure/hub/main.tf

Changes:
* Remove region loop from azure/hub

azure/hub: Remove region loop

---

modules/kubernetes/aad-pod-identity/main.tf
modules/kubernetes/csi-secrets-store-provider-azure/main.tf
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/kyverno/main.tf
modules/kubernetes/loki/README.md
modules/kubernetes/loki/main.tf
modules/kubernetes/loki/variables.tf
modules/kubernetes/opa-gatekeeper/main.tf

Moves version values from locals to be set in the `helm_release` resource.
Fixes #122

Make version values explicit

---

modules/azure/core/README.md
modules/azure/core/storage.tf
modules/azure/core/variables.tf

azure/core: optional storage account

---

modules/azure/governance-regional/README.md
modules/azure/governance-regional/rg.tf
modules/azure/governance-regional/variables.tf
validation/azure/governance-regional/main.tf

azure/governance-regional: add optional resource group lock

---

modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl

kubernetes/ingress-nginx: configure externalTrafficPolicy

---

modules/kubernetes/fluxcd-v2-azdo/main.tf

Fixes a small bug in the azdo proxy config

Replace repo with proj in azdo-proxy secret

---

modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/k8s-limit-range.tf
modules/kubernetes/aks-core/variables.tf

kubernetes/aks-core: Add limit range by default

---

modules/azure/governance-global/README.md
modules/azure/governance-global/outputs.tf
modules/azure/governance-regional/README.md
modules/azure/governance-regional/aad-group-rg.tf
modules/azure/governance-regional/aad-group-sub.tf
modules/azure/governance-regional/delegate-kv-sp.tf
modules/azure/governance-regional/delegate-kv.tf
modules/azure/governance-regional/delegate-se.tf
modules/azure/governance-regional/sp-sub-reader.tf
modules/azure/governance-regional/sp.tf
modules/azure/governance-regional/variables.tf
validation/azure/governance-regional/main.tf

Closes #192 
Move from:
```terraform
module "governance_global" {
source = "../../../github/terraform-modules/modules/azure/governance-global"
environment                  = local.environment
subscription_name            = local.subscription_name
owner_service_principal_name = local.owner_service_principal_name
delegate_sub_groups          = local.delegate_sub_groups
resource_group_configs       = local.resource_group_configs
}
module "governance_regional" {
depends_on = [ modules.governance_global ]
source = "../../../github/terraform-modules/modules/azure/governance-regional"
environment                  = local.environment
location_short               = local.location_short
location                     = local.location
core_name                    = local.core_name
subscription_name …
```

azure/governance-regional: Move from depends_on to output/variable

---

modules/kubernetes/aad-pod-identity/templates/values.yaml.tpl

Fixes breaking change in chart values.
https://azure.github.io/aad-pod-identity/docs/#v17x-breaking-change

Fix breaking values change in aad-pod-id chart

---

modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/opa-gatekeeper/README.md
modules/kubernetes/opa-gatekeeper/files/gatekeeper-values.yaml
modules/kubernetes/opa-gatekeeper/locals.tf
modules/kubernetes/opa-gatekeeper/main.tf
modules/kubernetes/opa-gatekeeper/templates/gatekeeper-library-values.yaml.tpl
modules/kubernetes/opa-gatekeeper/variables.tf
modules/kubernetes/prometheus/main.tf
validation/kubernetes/opa-gatekeeper/main.tf

Remove Kyverno and replace it with the latest gatekeeper mutation feature.

OPA Gatekeeper mutation

---

modules/kubernetes/README.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/goldpinger/README.md
modules/kubernetes/goldpinger/main.tf
modules/kubernetes/goldpinger/templates/values.yaml.tpl
modules/kubernetes/goldpinger/variables.tf
modules/kubernetes/prometheus/README.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitor.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/values.yaml
modules/kubernetes/prometheus/main.tf
modules/kubernetes/prometheus/templates/values-extras.yaml.tpl
modules/kubernetes/prometheus/variables.tf
validation/kubernetes/goldpinger/main.tf

This change adds goldpinger with a servicemonitor to scrape its metrics.
Closes #269

Add goldpinger

---

Makefile

Run make validate in paralell

---

modules/kubernetes/prometheus/charts/prometheus-extras/values.yaml
modules/kubernetes/prometheus/templates/values-extras.yaml.tpl

Set default values for alertmanager

---

modules/kubernetes/falco/templates/falco-values.yaml.tpl

This is to get less alarms from falco.
None of these images does anything strange

Add images that is okay to talk to k8s api

---

modules/kubernetes/falco/templates/falco-values.yaml.tpl

Reverts XenitAB/terraform-modules#279

Revert "Add images that is okay to talk to k8s api"

---

modules/kubernetes/aks-core/modules.tf
modules/kubernetes/opa-gatekeeper/locals.tf

Add allowed priority names

---

modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-azdo/templates/azdo-proxy-values.yaml.tpl
modules/kubernetes/ingress-healthz/main.tf
modules/kubernetes/ingress-healthz/templates/values.yaml.tpl
modules/kubernetes/reloader/main.tf
modules/kubernetes/xenit/main.tf
modules/kubernetes/xenit/templates/values.yaml.tpl

This change adds or fixes priority class names to the following modules:
* xenit
* ingress-healthz
* reloader
* azdo-proxy

Fix priority class names

---

modules/kubernetes/falco/templates/falco-values.yaml.tpl

It's secure for datadog to talk to the k8s api

Add datadoghq as ignored image in falco rule

---

modules/kubernetes/azad-kube-proxy/main.tf
modules/kubernetes/azad-kube-proxy/templates/values.yaml.tpl
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/eks-core/variables.tf
validation/kubernetes/eks-core/main.tf

Creating a bad PR where I also do a change to AZAD by adding a annotation to it.
I also bump the AZAD helm version

Add fluxcd EKS core

---

modules/kubernetes/aks-core/modules.tf

During a upgrade to AKS 1.20 calcio-system starts to getting used also in AKS.

Add calico-system to ignore list

---

modules/kubernetes/linkerd/main.tf
modules/kubernetes/linkerd/templates/values-cni.yaml.tpl

This to solve issues with linkerd not starting on a node where the CNI is fully online.
See: https://github.com/linkerd/linkerd2/issues/2219

Add linkerd initContainer

---

modules/kubernetes/datadog/README.md
modules/kubernetes/datadog/variables.tf

Causes issues for docusaurus to generate docs site

Remove HTML tag from variables

---

.github/workflows/trigger-docs-site.yaml

update from home repo to xenitab.github.io

---

.gitignore
Makefile
validation/kubernetes/cluster-autoscaler/main.tf
validation/kubernetes/csi-secrets-store-provider-aws/main.tf

`make validate` doesn't error if directory doesn't exist

Fix validation

---

modules/azure/core/README.md
modules/azure/core/outputs.tf

add outputs to azure/core

---

modules/kubernetes/aks-core/modules.tf
modules/kubernetes/ingress-nginx/README.md
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/ingress-nginx/templates/values.yaml.tpl
modules/kubernetes/ingress-nginx/variables.tf

Thanks to this datadog will be able to get metrics from nginx

Add datadog_enabled to ingress-nginx

---

README.md
modules/aws/README.md
modules/aws/core/main.tf
modules/aws/core/route53.tf
modules/aws/core/vpc.tf
modules/aws/eks-global/README.md
modules/aws/eks-global/aad-group.tf
modules/aws/eks-global/eks.tf
modules/aws/eks-global/kms.tf
modules/aws/eks-global/locals.tf
modules/aws/eks-global/main.tf
modules/aws/eks-global/outputs.tf
modules/aws/eks-global/variables.tf
modules/aws/eks-global/velero.tf
modules/aws/eks/README.md
modules/aws/eks/eks.tf
modules/aws/eks/iam.tf
modules/aws/eks/main.tf
modules/aws/eks/variables.tf
modules/azure/README.md
modules/kubernetes/README.md

This change aims to document an AWS specific style guide and implement it in all AWS resources.

Add AWS style guide

---

modules/kubernetes/opa-gatekeeper/main.tf

* Change back to upstream OPA helm chart.
* Solves #381

Set OPA helm release to 3.6.0

---

modules/kubernetes/datadog/main.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/eks-core/variables.tf

* Upgrade datadog helm chart to 0.7.0

Enable datadog in eks-core

---

modules/aws/eks-global/README.md
modules/aws/eks-global/delegate-eks-rg.tf
modules/aws/eks-global/variables.tf
validation/aws/eks-global/main.tf

We are seeing missed AD groups in EKS and this should fix it

Add missing delegate group config

---

modules/kubernetes/README.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/starboard/README.md
modules/kubernetes/starboard/main.tf
modules/kubernetes/starboard/templates/starboard-values.yaml.tpl
modules/kubernetes/starboard/variables.tf
validation/kubernetes/starboard/main.tf

Install a seperate trivy instance on the cluster to store the
vulnerability database.

Add aquasec starboard to xkf

---

CHANGELOG.md
modules/azure/README.md

This PR adds some additional information about Azure AD Graph deprecation.

add more info regarding aad graph deprecation

---

CHANGELOG.md

This PR prepares for the 2021.11.1 release.

prepare changelog for 2021.11.1 release

---

CHANGELOG.md
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/prometheus.yaml

This change aims to increase the stability of prometheus by tuning certain parameters.

Set resource request for prometheus and update remote write config

---

CHANGELOG.md
modules/kubernetes/opa-gatekeeper/templates/gatekeeper-values.yaml.tpl

Increase gatekeeper-audit memory request to 750Mi

---

modules/azure/aks/aks.tf

Just to make things more readable. Kept as a separate PR to make it easier to check.

Format node configuration

---

CHANGELOG.md
modules/kubernetes/aks-core/k8s-cluster-role.tf
modules/kubernetes/starboard/main.tf
modules/kubernetes/starboard/templates/starboard-values.yaml.tpl

* Upgrade trivy and starboard helm chart

Starboard scan for more severitys

---

CHANGELOG.md
modules/kubernetes/starboard/main.tf
modules/kubernetes/starboard/templates/starboard-values.yaml.tpl

* enable scanning the latest replicaset in a deployment.
* Set ttl of the vulnerability report to automatically be recreated.
* Solves: #515

Update starboard to 0.14.0

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf

Enable prometheus monitoring for grafana-agent.

Enable grafana-agent in Prometheus

---

CHANGELOG.md
modules/kubernetes/vpa/templates/goldilocks-values.yaml.tpl

Adds resource request & limits for goldilocks

Add resource requests & limits for goldilocks

---

CHANGELOG.md
modules/kubernetes/aks-core/k8s-cluster-role.tf

Add secretProviderClass CRD to existing clusterRole "custom_resource_edit"
Fixes #559

Add SecretProviderClass CRD to ClusterRole

---

CHANGELOG.md
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/Chart.yaml
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/templates/monitors.yaml
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/templates/pod-logs.yaml
modules/kubernetes/prometheus/README.md

Add ingress-nginx metrics and logs scraping to grafana-agent

---

CHANGELOG.md
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/Chart.yaml
modules/kubernetes/grafana-agent/charts/grafana-agent-extras/templates/pod-logs.yaml

Human error copy paste issue I guess

Fix podLogs spacing

---

CHANGELOG.md
modules/kubernetes/node-local-dns/charts/node-local-dns/Chart.yaml
modules/kubernetes/node-local-dns/charts/node-local-dns/templates/nodelocaldns.yaml

Add prefetch config to allow automatic updates of well used endpoints.
For more information about the default values see: https://coredns.io/plugins/cache/

Update node-local-dns dns config with prefetch cache config

---

CHANGELOG.md
modules/kubernetes/opa-gatekeeper/locals.tf
modules/kubernetes/opa-gatekeeper/main.tf

Drop CAP_SYS_ADMIN from all containers in the cluster just like NET_RAW.
Update grafana-library to version 0.10.0.

Drop CAP_SYS_ADMIN in default constraints

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/main.tf
modules/azure/aks-global/outbound-ips.tf
modules/azure/aks-global/velero.tf
modules/azure/aks/README.md
modules/azure/aks/aks.tf
modules/azure/aks/main.tf
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/core/README.md
modules/azure/core/main.tf
modules/azure/github-runner/README.md
modules/azure/github-runner/main.tf
modules/azure/governance-global/README.md
modules/azure/governance-global/main.tf
modules/azure/governance-regional/README.md
modules/azure/governance-regional/main.tf
modules/azure/hub/README.md
modules/azure/hub/main.tf
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf

Major upgrade of the azurerm provider. Will include some parameter changes but should not affect anything outside the modules.

Upgrade azurerm provider to 3.1.0

---

CHANGELOG.md
modules/kubernetes/promtail/templates/values.yaml.tpl

Promail shall run on all nodes and hence tolerate everything.

Add toleration for Promtail

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/main.tf

This PR fixes two new security disclosures.
CVE-2021-25746
CVE-2021-25745

Update Ingress Nginx version

---

CHANGELOG.md
modules/kubernetes/opa-gatekeeper/locals.tf

* pod-default-seccomp
* disable default mount of SA token

Add new default assigns to OPA lib

---

CHANGELOG.md
modules/aws/eks/variables.tf
modules/azure/aks/variables.tf
validation/aws/eks/main.tf
validation/azure/aks/main.tf

Add check for Kubernetes version

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/main.tf
modules/azure/aks/README.md
modules/azure/aks/main.tf
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/core/README.md
modules/azure/core/main.tf
modules/azure/github-runner/README.md
modules/azure/github-runner/main.tf
modules/azure/governance-global/README.md
modules/azure/governance-global/main.tf
modules/azure/governance-regional/README.md
modules/azure/governance-regional/main.tf
modules/azure/hub/README.md
modules/azure/hub/main.tf
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf

Adds support to disable run command and update node labels without recreating the node pool.

Update azurerm provider version

---

CHANGELOG.md
modules/kubernetes/node-ttl/main.tf

Fixes a configuration error for the node-ttl OCI registry.

Fix node-ttl OCI registry

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/networkpolicy.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/networkpolicy.tf

Allow datadog ingress by default to tenant namespace

---

CHANGELOG.md
modules/kubernetes/node-ttl/main.tf
modules/kubernetes/node-ttl/templates/values.yaml.tpl

Sets resource request and limits to node-ttl

Set resource request and limits to node ttl

---

CHANGELOG.md
modules/kubernetes/linkerd/main.tf

Updates Linkerd to latest versions

Update linkerd versions

---

CHANGELOG.md
modules/kubernetes/cert-manager/templates/values.yaml.tpl

This bug was created in: https://github.com/XenitAB/terraform-modules/pull/733.

Fix cert-manager webhook AWS config

---

CHANGELOG.md
modules/aws/eks/eks.tf

Fix https://github.com/XenitAB/terraform-modules/issues/655

upgrade AWS calico to 3.24

---

modules/azure/aks/aad-group.tf
modules/azure/aks/aks.tf
modules/azure/aks/locals.tf
modules/azure/aks/main.tf

No resource changes, just some moving of resources to make AKS more readable.

Restructure AKS module to be more readable

---

CHANGELOG.md
modules/azure/core/delegate-service-endpoint-join.tf

This to be able to migrate between subscriptions in Azure in the same RG.

Add unique_suffix to core delegate

---

.github/workflows/check.yaml
CHANGELOG.md
modules/aws/.tflint.hcl
modules/aws/eks-core/outputs.tf
modules/azure/.tflint.hcl
modules/kubernetes/.tflint.hcl

This is needed to be able to support optionals in tflint in #836

Update TFLint to 0.42

---

CHANGELOG.md
modules/kubernetes/fluxcd-v2-azdo/main.tf
modules/kubernetes/fluxcd-v2-github/main.tf

This update fixes metrics cardinality caused by the path being included in the time series.

Update git-auth-proxy version

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/acr.tf
modules/azure/aks-global/variables.tf
modules/azure/aks-regional/README.md
modules/azure/aks-regional/trivy.tf
modules/azure/aks-regional/variables.tf

This change is required to support legacy solutions.

Allow overriding ACR name

---

CHANGELOG.md
modules/kubernetes/promtail/templates/values.yaml.tpl

Fix undocumented changes to values files.

Fix promtail configuration

---

CHANGELOG.md
modules/kubernetes/ingress-nginx/main.tf
modules/kubernetes/prometheus/charts/prometheus-extras/Chart.yaml
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitors.yaml

Solves #794 and also adds support for k8s 1.25

Upgrade ingress-nginx to 4.4.0

---

CHANGELOG.md
modules/azure/core/README.md
modules/azure/core/log.tf
modules/azure/core/variables.tf
validation/azure/core/main.tf

The log storage account should constantly get audit logs sent to it.
If not we should notice it.

Monitor if logs is missing

---

CHANGELOG.md
modules/azure/core/README.md
modules/azure/core/locals.tf
modules/azure/core/subnets.tf
modules/azure/core/variables.tf

Core/azurerm_subnet: Make "private_endpoint_network_policies_enabled" configurable

Fixes #942: Core/azurerm_subnet: Make private_endpoint_network_policies_enabled configurable

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/prometheus/README.md
modules/kubernetes/prometheus/charts/prometheus-extras/templates/monitors.yaml
modules/kubernetes/prometheus/main.tf
modules/kubernetes/prometheus/templates/values-extras.yaml.tpl
modules/kubernetes/prometheus/variables.tf

The service monitor was missing for Spegel so this change adds it.

Add Spegel service monitor

---

CHANGELOG.md
modules/azure/core/log.tf

The dynamic logging haven't worked as well as we hoped.

Update audit log alert criteria

---

CHANGELOG.md
modules/azure/core/log.tf

Change audit log alert window_size and frequency

---

CHANGELOG.md
modules/kubernetes/spegel/main.tf
modules/kubernetes/spegel/templates/values.yaml.tpl

This change also sets resource requests and limits for Spegel.

Update Spegel to v0.0.5

---

CHANGELOG.md
modules/kubernetes/node-local-dns/charts/node-local-dns/Chart.yaml
modules/kubernetes/node-local-dns/charts/node-local-dns/templates/nodelocaldns.yaml
modules/kubernetes/node-local-dns/charts/node-local-dns/values.yaml

We need to migrate to the new Kubernetes image registry. Updated the image version while I am at it.

Update node-local-dns and move to using registry.k8s.io

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf

The VPA module CRD was not correct and the versions were not updated so this change fixes that,

Fix CRD versions

---

CHANGELOG.md

Prepare 2023.04.1

---

CHANGELOG.md
modules/kubernetes/datadog/templates/kustomization.yaml.tpl

Adds health checks to Datadog deployment.

Add health checks to Datadog

---

CHANGELOG.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf
modules/kubernetes/eks-core/README.md
modules/kubernetes/eks-core/main.tf
modules/kubernetes/fluxcd-v2-github/README.md
modules/kubernetes/fluxcd-v2-github/main.tf

This fixes the blocker of generating GitHub application tokens.

Update GitHub Terraform provider

---

CHANGELOG.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/eks-core/modules.tf
modules/kubernetes/spegel/README.md
modules/kubernetes/spegel/main.tf
modules/kubernetes/spegel/templates/kustomization.yaml.tpl
modules/kubernetes/spegel/templates/spegel.yaml.tpl
modules/kubernetes/spegel/variables.tf
validation/kubernetes/spegel/main.tf

Need to remove Spegel state.
```
tf state rm 'module.aks1_core.module.spegel["spegel"].helm_release.this' 'module.aks1_core.module.spegel["spegel"].kubernetes_namespace.this'
```

Migrate spegel to install with Flux

---

CHANGELOG.md
modules/azure/aks/README.md
modules/azure/aks/aks.tf

[Migrate diagnostic settings storage retention to Azure Storage lifecycle management - Azure Monitor](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy?tabs=portal).

Migrate diagnostic settings

---

CHANGELOG.md
modules/azure/aks/aks.tf

Logic for enabling Defender was reversed. Fixed now.

Fix reveresed logic for enabling defender

---

CHANGELOG.md
modules/azure/aks-global/README.md
modules/azure/aks-global/main.tf
modules/azure/aks-regional/README.md
modules/azure/aks-regional/main.tf
modules/azure/aks/README.md
modules/azure/aks/main.tf
modules/azure/azure-pipelines-agent-vmss/README.md
modules/azure/azure-pipelines-agent-vmss/main.tf
modules/azure/core/README.md
modules/azure/core/main.tf
modules/azure/github-runner/README.md
modules/azure/github-runner/main.tf
modules/azure/governance-global/README.md
modules/azure/governance-global/main.tf
modules/azure/governance-regional/README.md
modules/azure/governance-regional/main.tf
modules/azure/hub/README.md
modules/azure/hub/main.tf
modules/azure/xkf-governance-global-data/README.md
modules/azure/xkf-governance-global-data/main.tf
modules/azure/xkf-governance-global/README.md
modules/azure/xkf-governance-global/main.tf
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf
modules/kubernetes/azure-policy/README.md
modules/kubernetes/azure-policy/main.tf

This PR bumps the version of the azurerm provider to 3.99.0.

Bump azurerm provider to v 3.99.0

---

modules/kubernetes/spegel/templates/spegel.yaml.tpl

update spegel to 0.0.23 and correction of acr repo, tested in sandbox and all good

chore: update spegel to 0.0.23

---

modules/kubernetes/cert-manager/templates/cert-manager.yaml.tpl
modules/kubernetes/external-dns/templates/external-dns.yaml.tpl
modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
modules/kubernetes/node-local-dns/templates/node-local-dns.yaml.tpl

Tested and all works fine in unbox-sand cluster.

chore: Update Ingress-nginx, Cert-manager and external-dns

---

modules/kubernetes/README.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/main.tf
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/popeye/README.md
modules/kubernetes/popeye/charts/popeye/.helmignore
modules/kubernetes/popeye/charts/popeye/Chart.yaml
modules/kubernetes/popeye/charts/popeye/templates/cluster-role-binding.yaml
modules/kubernetes/popeye/charts/popeye/templates/cluster-role.yaml
modules/kubernetes/popeye/charts/popeye/templates/config-map.yaml
modules/kubernetes/popeye/charts/popeye/templates/cronjob.yaml
modules/kubernetes/popeye/charts/popeye/templates/pvc.yaml
modules/kubernetes/popeye/charts/popeye/templates/secret.yaml
modules/kubernetes/popeye/charts/popeye/templates/service-account.yaml
modules/kubernetes/popeye/charts/popeye/templates/storage-class.yaml
modules/kubernetes/popeye/charts/popeye/values.yaml.tpl
modules/kubernetes/popeye/main.tf
modules/kubernetes/popeye/variables.tf
modules/kubernetes/popeye/workload-identity.tf
validation/kubernetes/popeye/main.tf

This PR adds support for the [popeye](https://github.com/derailed/popeye) k8s live cluster linter.

feat: add support for popeye k8s linter

---

modules/kubernetes/README.md
modules/kubernetes/aks-core/README.md
modules/kubernetes/aks-core/modules.tf
modules/kubernetes/aks-core/variables.tf
modules/kubernetes/litmus/README.md
modules/kubernetes/litmus/main.tf
modules/kubernetes/litmus/templates/kustomization.yaml.tpl
modules/kubernetes/litmus/templates/litmuschaos.yaml.tpl
modules/kubernetes/litmus/variables.tf
validation/kubernetes/aks-core/main.tf
validation/kubernetes/litmus/main.tf

This PR adds support for basic deployment of LitmusChaos in XKS clusters.

feat: add support for LitmusChaos

---

modules/kubernetes/aks-core/modules.tf
modules/kubernetes/external-dns/templates/external-dns.yaml.tpl
modules/kubernetes/fluxcd/templates/cluster-tenants.yaml
modules/kubernetes/grafana-k8s-monitoring/README.md
modules/kubernetes/grafana-k8s-monitoring/main.tf
modules/kubernetes/grafana-k8s-monitoring/templates/monitors.yaml.tpl
modules/kubernetes/grafana-k8s-monitoring/variables.tf

chore: consolidating all monitoring resources to avoid CRD issues

---

modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl

This PR fixes a critical vulnerability that allows RCE without authentication

chore: upgrade nginx controller to latest version

---

modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl

This PR fixes a broken template in the `grafana-k8s-monitoring` chart.

fix: broken grafana-k8s-monitoring template

---

modules/kubernetes/argocd/templates/argocd-values.yaml.tpl

This PR enabled metrics collecting from ArgoCD.

feat: enable argocd metrics

---

modules/kubernetes/karpenter/main.tf
modules/kubernetes/karpenter/templates/node-classes.yaml.tpl

This PR upgrades karpenter to the latest version.

chore: upgrade karpenter to 1.4.0
